# -*- coding: utf-8 -*-
"""Rebalanced option sets for deck_questions_c.py, questions 161 to 240.

This module holds decks 17 to 24, which is exactly the q161-240 range, so every
question is replaced. Apply with:

    python3 rebalance_options.py deck_questions_c.py --offset 160 --apply

All four options in each question sit within a narrow length band, the correct
one is deliberately not the longest in most questions, and neither absolutes nor
hedges are confined to one side.

REPLACEMENTS[question_number] = (correct, [d1, d2, d3])
"""

REPLACEMENTS = {

    # ---- Deck 17: eRACH ----
    161: ("Satellites move fast, so the best one to reach changes within milliseconds",
          ["The count of satellites in view changes as the constellation is expanded",
           "Ground terminals move between the beams faster than the network can track them",
           "The preamble set is re-randomised by the network at each access window"]),
    162: ("1 to 5 ms, which makes acknowledgement schemes slow and wasteful of retries",
          ["1 to 5 ms, which is short enough for acknowledgement schemes to work as is",
           "20 to 60 ms, which forces most protocols to abandon acknowledgements outright",
           "Under 1 ms, so delay affects throughput but not the design of a protocol"]),
    163: ("Where the satellite should be, and whether its own last attempt collided",
          ["The queue length and preamble choice of each neighbouring terminal",
           "A schedule the network broadcasts at the start of each access window",
           "The aggregate collision rate as measured across the whole spot beam"]),
    164: ("Whether to access now and which satellite, or to back off and wait",
          ["Which preamble index to select from the pool shared across terminals",
           "How much transmit power should be applied to the outgoing preamble",
           "Whether to use the terrestrial network in place of the satellite one"]),
    165: ("The access pattern arises from independent learning, with no signalling",
          ["The protocol emerged from the standardisation process over several releases",
           "The satellite emerges into view and then broadcasts the access schedule",
           "New preambles are generated on demand as further devices join the network"]),
    166: ("About 55 percent higher throughput and near twice lower access delay",
          ["About 31 percent higher throughput and near four times lower access delay",
           "About 55 percent lower collision rate and near twice higher throughput",
           "Twice the throughput and about 55 percent lower access delay overall"]),
    167: ("The balance between maximising throughput and avoiding collisions",
          ["The learning rate applied to the actor-critic network during training",
           "The number of candidate satellites a terminal is allowed to consider",
           "The length of the backoff window, expressed in whole milliseconds"]),
    168: ("Computational complexity set against size, weight and power limits",
          ["Sensitivity to the accuracy of the predicted satellite position",
           "A collision tolerance higher than that of the standard protocol",
           "The absence of any coordination between neighbouring devices"]),
    169: ("Expected position is one of two inputs, so error corrupts the policy",
          ["The terminal must report its own position before it is granted access",
           "Positioning error changes which preamble the terminal ends up choosing",
           "The satellite cannot compute a reward without an accurate position fix"]),
    170: ("Standard access ignores satellite mobility, so collisions and delay rise",
          ["Standard access cannot operate beyond a certain orbital velocity threshold",
           "Constellations have far too few preambles for the number of devices served",
           "Multi-agent learning is required by the specification for NTN access"]),

    # ---- Deck 18: RIS ----
    171: ("A satellite needs a clear view, and an obstruction removes the link entirely",
          ["The satellite beam is too wide to serve individual users efficiently",
           "The satellite cannot generate enough beams for the users in its cell",
           "Atmospheric absorption removes the link at the higher frequencies used"]),
    172: ("Each element sets its own phase, so the reflections add in one direction",
          ["Each element amplifies the incident signal before it is re-radiated",
           "The surface rotates physically so as to face the intended receiver",
           "The surface shifts the signal to another frequency before reflecting"]),
    173: ("Each element has an amplifier, so amplitude as well as phase is set",
          ["It applies discrete phase steps rather than continuous phase control",
           "It responds differently across the frequencies within a wide band",
           "It is mounted on the satellite itself rather than on a building"]),
    174: ("Digital RIS, using a small number of fixed discrete phase states",
          ["Tunable analog RIS, using varactors for continuous phase",
           "Hybrid RIS, mixing passive elements with amplified ones",
           "Frequency-selective RIS, responding across several bands"]),
    175: ("Frequency-selective RIS, whose elements vary across frequency",
          ["Passive RIS, because it introduces no gain that varies with frequency",
           "Hybrid RIS, because it mixes passive elements with active ones",
           "Digital RIS, because a 1-bit phase control is frequency independent"]),
    176: ("The two hops multiply rather than add, so combined loss is severe",
          ["The panel must exceed the wavelength of the incident signal to work",
           "A large panel is needed to dissipate heat produced by its controller",
           "Regulations set a minimum aperture for reflecting satellite signals"]),
    177: ("The channel must be estimated elsewhere before the phases are computed",
          ["The surface cannot be given an identity of its own in the network",
           "The surface cannot confirm its reflection reached the intended user",
           "The surface cannot be updated once it has been installed anywhere"]),
    178: ("A large panel breaks the simple distance model far-field assumes",
          ["The panel heats the surrounding structure when used at close range",
           "The panel reflects into its own controller over short distances",
           "The panel cannot be used indoors because of reflections off walls"]),
    179: ("It gives a second path, so another spatial stream becomes possible",
          ["It doubles the bandwidth that is made available on the existing path",
           "It lets the satellite reuse one frequency across adjacent beams",
           "It compresses the data being carried before reflecting it onward"]),
    180: ("A candidate for 6G, not yet present in any released standard",
          ["Specified in Release 18 as a part of the 5G-Advanced work",
           "Standardised by the ITU for satellite applications alone",
           "Withdrawn from standardisation after Release 17 studies"]),

    # ---- Deck 21: uplink synchronisation without GNSS ----
    181: ("5G NR, regenerative payload with onboard base station, LEO, CP-OFDM uplink",
          ["5G NR, transparent bent-pipe payload, GEO orbit, with SC-FDMA on the uplink",
           "LTE, regenerative payload in MEO orbit, with CP-OFDM used on the uplink",
           "5G NR, transparent payload in LEO, with OFDMA on the downlink alone"]),
    182: ("A broadcast common part, a device-computed part, and a measured trim",
          ["An open-loop part, a closed-loop part, and a Doppler pre-compensation",
           "A service link part, a feeder link part, and an inter-satellite part",
           "A coarse part, a fine part, and a fractional subcarrier correction"]),
    183: ("The open-loop calculation, since the device cannot locate itself",
          ["The closed loop, since the base station can no longer measure arrival",
           "The common broadcast, since the network is unable to compute a value",
           "The cyclic prefix, since it can no longer absorb the delay spread"]),
    184: ("First transmissions land far outside the window, so nothing is ever measured",
          ["The closed loop corrects frequency error but not any of the timing error",
           "The base station cannot address a command to an unsynchronised device",
           "The closed loop requires a navigation timestamp inside each command"]),
    185: ("Motion changes the delay, so arrival drift reveals the correction",
          ["The satellite broadcasts its own clock drift for the device to copy",
           "Oscillator drift in the device is proportional to propagation delay",
           "Arrival drift is removed by simply lengthening the cyclic prefix"]),
    186: ("Device latitude, satellite longitude and the distance between the two",
          ["Device velocity, satellite velocity and the relative Doppler shift",
           "Timing advance, frequency offset and the oscillator drift rate",
           "Beam index, elevation angle to the satellite and the slant range"]),
    187: ("Robust performance, converging quickly onto accurate values",
          ["Zero computational cost incurred on the user device itself",
           "Complete independence from the received downlink signal",
           "Equal accuracy at the beam edge and at the beam centre"]),
    188: ("Accurate near the beam centre, and well off out near the beam edge",
          ["Accurate for low orbits, but failing badly for geostationary",
           "Accurate at first, but drifting away as the satellite moves on",
           "Working only for devices that already hold a navigation fix"]),
    189: ("Whether the uplink arrived early, late, or inside the window",
          ["The Doppler shift carried by the arriving uplink carrier signal",
           "The received power of the uplink measured against a target",
           "The number of retransmissions the device has already tried"]),
    190: ("Alternative methods allow uplink synchronisation without GNSS",
          ["GNSS is unavoidable for uplink synchronisation in any NTN",
           "Uplink synchronisation is unnecessary with an onboard base station",
           "GNSS is replaced by an atomic clock placed inside each device"]),

    # ---- Deck 22: deep reinforcement learning for SAGIN ----
    191: ("Satellites, aerial platforms and ground infrastructure as one system",
          ["A satellite constellation that also carries an Earth observation payload",
           "A terrestrial network whose backhaul happens to be over satellite",
           "A network in which each user device is able to act as a relay"]),
    192: ("Sharing limited link and compute resources so service stays fair",
          ["Giving each satellite a fixed share of the spectrum at launch time",
           "Deciding which ground stations will serve which orbital planes",
           "Allocating onboard storage for traffic that has been buffered"]),
    193: ("Scarce spectrum, limited onboard energy, and shifting user demand",
          ["Orbital debris, the cost of launch, and gaining regulatory approval",
           "Handover failure, loss of packets, and jitter on the delivered stream",
           "Key distribution, device authentication, and leakage of private data"]),
    194: ("Available power, bandwidth, signal quality and channel information",
          ["The total reward accumulated over the course of the previous episode",
           "The set of actions that the agent has not yet attempted to take",
           "The orbital elements of each satellite within the constellation"]),
    195: ("Channel allocation, power control and selection of an access point",
          ["Execution of a handover and the shaping of a beam, and nothing else",
           "Shaping of the reward signal and updating of the learned policy",
           "Broadcast of ephemeris and signalling of the timing advance value"]),
    196: ("Service quality, experienced quality, and efficient use of spectrum",
          ["Rate of collision, delay before access, and the energy spent per bit",
           "Achieved throughput, end-to-end latency, and the orbital altitude",
           "Area of coverage, count of satellites, and the rate of handover"]),
    197: ("Deep Q-Network, which scores each option and picks the best",
          ["Deterministic policy gradient, which outputs a real value",
           "Proximal policy optimisation, which updates conservatively",
           "Soft actor-critic, which explores widely while converging reliably"]),
    198: ("Deterministic policy gradient, giving a continuous output",
          ["Deep Q-Network, which selects from among a set of discrete choices",
           "Proximal policy optimisation, which updates step by step",
           "Twin delayed variant, which reduces overestimation error"]),
    199: ("Position placement, spectrum and power sharing, and edge computing",
          ["Beam hopping, spectrum provisioning, and allocation of transmit power",
           "Drone placement in three dimensions, channel estimation, interference",
           "Traffic offloading, base station selection, and routing to the cloud"]),
    200: ("Scale, an environment that will not hold still, and hard deadlines",
          ["Scarce training data, the simulation gap, and certification of policy",
           "Self-interference, node synchronisation, and onboard compute limits",
           "Bandwidth overhead, handshake latency, and hardened slow processors"]),

    # ---- Deck 23: HARQ ----
    201: ("It keeps the failed copy and combines it with the retransmission",
          ["It retransmits automatically without waiting for any acknowledgement",
           "It corrects errors outright without ever needing a retransmission",
           "It applies correction only after a first retransmission has failed"]),
    202: ("The same coded packet again, combined with the stored soft bits",
          ["A different set of parity bits produced by that very same encoder",
           "Just the systematic bits, without any of the parity bits sent",
           "A shorter packet holding just the bits that failed to decode"]),
    203: ("Different parity is sent, so punctured bits now reach the receiver",
          ["The retransmission is sent at a noticeably higher power level",
           "The receiver discards the first copy before decoding the second",
           "The retransmission is carried using an entirely different modulation"]),
    204: ("Every process waits on its acknowledgement, so none is left free",
          ["The soft buffer overflows before the acknowledgement can arrive",
           "The acknowledgement expires and is then discarded by the receiver",
           "The receiver cannot decode a packet arriving after a long delay"]),
    205: ("16 by default, raised to as many as 32 for non-terrestrial use",
          ["8 by default, raised to as many as 16 for non-terrestrial use",
           "16 by default, raised to as many as 64 for any non-terrestrial use",
           "32 by default, raised to as many as 64 for non-terrestrial use"]),
    206: ("No acknowledgement is sent, so strong coding carries the load",
          ["Just negative acknowledgements are sent, halving the feedback load",
           "Feedback is sent to the gateway rather than to the satellite",
           "Feedback is deferred until the end of the satellite's pass"]),
    207: ("At the link control layer, slower but without stalling the pipe",
          ["At the physical layer, by using a more robust modulation scheme",
           "At the application layer, by requesting the whole file once more",
           "On the satellite, which retransmits from a buffer of its own"]),
    208: ("More processes raise throughput and call for more memory",
          ["Longer timers speed failure detection and use less memory",
           "Disabling feedback speeds recovery and avoids false alarms",
           "Onboard processing gives the slowest loop at the lowest cost"]),
    209: ("On the ground, so the loop crosses service and feeder links",
          ["On the satellite, so the loop covers just the service link",
           "Inside the core network, so the loop crosses to the internet",
           "Split across satellite and gateway, one process on each side"]),
    210: ("The station is aboard, so the loop closes over the service link",
          ["The loop disappears, since errors are corrected while on board",
           "The loop is extended to take in the inter-satellite link as well",
           "The loop is moved up to the link control layer automatically"]),

    # ---- Deck 24: network digital twinning ----
    211: ("A virtual replica continuously updated from real-world data",
          ["A backup constellation held in reserve in case of a failover",
           "A simulation model built once during the design phase only",
           "A duplicate of the control software running on the ground"]),
    212: ("Rapid topology change, as links are created and broken",
          ["The gradual decay of orbits across the mission lifetime",
           "The limited number of ground stations licensed globally",
           "The fixed bandwidth agreed at constellation design time"]),
    213: ("Higher latency, unstable routing, slow fault detection, more cost",
          ["Orbital debris, the risk of collision, and end-of-life disposal cost",
           "Spectrum interference, cross-border rules, and licensing delay",
           "Compromised keys, replay attacks, and exposure of identities"]),
    214: ("A global controller and a central twin of the whole network",
          ["An edge twin maintained for each individual ground station",
           "The physical satellites together with their telemetry links",
           "A local controller managing beam and radio resource allocation"]),
    215: ("Beam and radio allocation, data processing, and fault diagnosis",
          ["Network verification, slice management, global optimisation",
           "Traffic engineering and modelling of the network as a whole",
           "Orbit determination and the broadcast of ephemeris to users"]),
    216: ("Collect, synchronise, simulate futures, evaluate, and then deploy",
          ["Observe, decide, act, learn, and then repeat the entire cycle",
           "Sense, optimise, act, learn, and finally verify the outcome",
           "Predict, measure, correct, verify, and log for later review"]),
    217: ("Lower latency, better routing, faster faults, lower cost",
          ["Higher orbits, wider coverage, and a longer satellite life",
           "Stronger encryption, better authentication, more privacy",
           "Larger constellations, cheaper launch, faster deployment"]),
    218: ("Twins must migrate as the satellites they model keep moving",
          ["Twins need re-certifying whenever network software is updated",
           "Twins cannot be transferred between different vendor platforms",
           "Twins lose their accumulated history whenever they are moved"]),
    219: ("Keeping model and network in step consumes link bandwidth",
          ["Synchronisation requires an atomic clock on each satellite",
           "The twin cannot run at all while synchronisation is running",
           "Synchronisation errors accumulate and cannot be corrected"]),
    220: ("A compromised twin could be used to disrupt the real network",
          ["The twin holds subscriber data that could be exposed by leak",
           "The twin's synchronisation traffic cannot be encrypted at all",
           "The twin can be used to locate satellites for physical attack"]),

    # ---- Predictive handover (unnumbered deck) ----
    221: ("On the ground you pass towers; in orbit the tower passes you",
          ["In orbit the user selects the satellite manually each session",
           "In orbit handovers occur only when the user physically moves",
           "In orbit the satellite hands over without telling the device"]),
    222: ("Many devices on one satellite must switch at nearly one time",
          ["A single device switching repeatedly between two satellites",
           "A burst of signalling brought on by the failure of a satellite",
           "Handovers triggered by atmospheric interference during storms"]),
    223: ("A device flips between two satellites because confidence is low",
          ["A device alternates between uplink and downlink of one satellite",
           "An acknowledgement bounces between the satellite and the gateway",
           "A beam sweeps back and forth across the very same ground cell"]),
    224: ("The decision returns after the satellite has already moved on",
          ["Satellite receivers cannot measure signal strength accurately",
           "Ground networks make no use of signal-strength triggers at all",
           "The satellite cannot store a measurement report while moving"]),
    225: ("A satellite's flight path follows fixed laws and is therefore predictable",
          ["Users follow movement patterns that repeat closely from day to day",
           "Radio interference in space is lower and so is more stable",
           "Satellites broadcast their planned handover schedule ahead"]),
    226: ("Backups and conditions set ahead, but the conditions are fixed",
          ["A predicted handover time, but no backup target is provided",
           "A fully learned policy, but no fallback if prediction fails",
           "A guaranteed target satellite, but only for users that are stationary"]),
    227: ("Forecast physical quantities from orbit models, or forecast signal series",
          ["Forecast user demand with a Markov chain, or forecast load with a filter",
           "Forecast orbital decay numerically, or forecast weather with a network",
           "Forecast beam occupancy with a scheduler, or handover counts by regression"]),
    228: ("Choosing a target satellite, or staying with the current one",
          ["Deciding whether or not to send a measurement report now",
           "Setting the transmit power to use for the next uplink slot",
           "Selecting which beam of the serving satellite ought to be used"]),
    229: ("It drops the measurement report and predicts the action directly",
          ["It adds a second measurement report in order to raise the confidence",
           "It moves the handover decision from the network to the device",
           "It replaces the reward function with a simple fixed threshold"]),
    230: ("It optimises handovers across all users rather than one link",
          ["It gives priority to aviation users ahead of all other traffic",
           "It routes each device down a fixed corridor through the sky",
           "It hands the decision to a human operator on the ground below"]),

    # ---- Trajectory optimization (unnumbered deck) ----
    231: ("Static deployment gives poor coverage, high delay and congestion",
          ["Satellites cannot be launched into any of the orbits that 6G requires",
           "Terrestrial stations cannot support the 6G modulation schemes",
           "Drones are barred from operating in the same airspace as aircraft"]),
    232: ("Static trajectories that do not adapt to where users actually are",
          ["The inability of any drone to operate above about 20 km of altitude",
           "The lack of a standardised air interface for aerial platforms",
           "An excessive amount of spectrum allocated to aerial platforms"]),
    233: ("Machine learning is a branch of AI that learns from the data",
          ["Artificial intelligence is a branch of machine learning",
           "They are two different names for one set of techniques",
           "Machine learning covers supervised problems, AI the rest"]),
    234: ("It learns by interaction, adapts, and optimises long-term reward",
          ["It requires no training data of any kind at any point before deployment",
           "It yields one fixed trajectory that avoids needing updates",
           "It runs on the ground, so the platform carries no compute"]),
    235: ("User positions, signal, battery, demand, obstacles and weather",
          ["Preamble collisions, backoff windows and the barring probabilities",
           "Ephemeris data, the timing advance and the Doppler shift value",
           "Slice identifiers, quality flows and the session context data"]),
    236: ("Coverage against energy, against delay and against interference",
          ["Altitude against the total flight time available to the platform",
           "Throughput against the number of platforms that are deployed",
           "Battery life against the number of users that can be served"]),
    237: ("More users covered, higher rate, lower delay and less energy",
          ["Higher altitude, wider beams and a longer duration of flight",
           "Fewer handovers, fewer beams and lower use of the bandwidth",
           "More platforms deployed and a larger radius of ground coverage"]),
    238: ("Quasi-stationary at about 20 km, serving users and backhauling",
          ["Low-altitude platforms giving coverage of hotspots when it is needed",
           "Orbital platforms providing wide-area broadcast services",
           "Ground platforms aggregating traffic from the fixed network"]),
    239: ("Airspace regulation, which limits where a platform is flown",
          ["The absence of any learning algorithm suited to the problem",
           "The inability to measure signal strength from a flying platform",
           "The lack of demand for any coverage across remote regions"]),
    240: ("Autonomous adaptive decisions improving coverage and efficiency",
          ["The removal of all the terrestrial infrastructure from the network",
           "One fixed trajectory that proves optimal for every deployment",
           "Coverage guarantees that do not depend on battery capacity"]),
}
